const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 300,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 1200,
    img: './images/item-2.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 500,
    img: './images/item-3.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 799,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 899,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 499,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 399,
    img: './images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 1299,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 579,
    img: './images/item-9.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'dosa',
    category: 'breakfast',
    price: 129,
    img: 'https://www.cookwithmanali.com/wp-content/uploads/2020/05/Masala-Dosa.jpg',
    desc: `A dosa (also dosai or dosha) is a thin pancake or crepe, originating from South India, made from a fermented batter predominantly consisting of lentils and rice. ... Its main ingredients are rice and black gram, ground together in a fine, smooth batter with a dash of salt, then fermented`,
  },
  {
    id: 11,
    title: 'pao bhaji',
    category: 'breakfast',
    price: 210,
    img: 'https://static.toiimg.com/thumb/52416693.cms?imgsize=789478&width=800&height=800',
    desc: `Pav Bhaji is essentially a ragout of boiled, mashed and slow simmered vegetables spiked with a tantalising array of spices and served to be lapped up with crusty pan fried bread, a dash of lemon and a lashing of sweet red onions. It is the most explosive of vegetarian flavours revealing themselves on your palate.`,
  },
  {
    id: 12,
    title: 'Vada Pav',
    category: 'breakfast',
    price: 99,
    img: 'https://www.cookwithmanali.com/wp-content/uploads/2018/04/Vada-Pav-500x500.jpg',
    desc: `Vada pav, alternatively spelt wada pao, ( listen) is a vegetarian fast food dish native to the state of Maharashtra. The dish consists of a deep fried potato dumpling placed inside a bread bun (pav) sliced almost in half through the middle. It is generally accompanied with one or more chutneys and a green chili pepper.`,
  },
  {
    id: 13,
    title: 'aloo parantha',
    category: 'breakfast',
    price: 49,
    img: 'https://www.shanazrafiq.com/wp-content/uploads/2016/03/2-DSC_0179.jpg',
    desc: `Aloo parathas consist of unleavened dough rolled with a mixture of mashed potato and spices, which is cooked on a hot tawa with butter or ghee. Aloo paratha is usually served with butter, chutney, or Indian pickles in different parts of northern and western India.`,
  },
  {
    id: 14,
    title: 'rajma chawal',
    category: 'lunch',
    price: 199,
    img: 'https://i2.wp.com/www.bharatzkitchen.com/wp-content/uploads/2020/08/Rajma-Chawal.jpg?fit=640%2C357&ssl=1',
    desc: `Rajma chawal is kidney beans served with boiled rice.`
  },
  {
    id: 15,
    title: 'kulche chhole',
    category: 'lunch',
    price: 299,
    img: 'https://static.toiimg.com/thumb/73514385.cms?imgsize=1468833&width=800&height=800',
    desc: `One of the best Indian snacks cum breakfast options out there is Chole kulche! Originated from the Punjab region, this dish is loved all over the country and is now making its way in the west too. A delicious combination of an all-purpose flour bread tossed in butter along with tangy and spicy chole, chole kulche is one such dish that we Indians just cannot resist.`,
  },
  {
    id: 16,
    title: 'Aloo Tikki',
    category: 'Snacks',
    price: 99,
    img: 'https://i.ytimg.com/vi/ipTEYc4xY54/maxresdefault.jpg',
    desc: `Aloo tikki is a golden fried-potato patty that is often stuffed with peas or dal and served with a variety of spicy chutneys and sometimes chickpeas, while aloo chaat is simply boiled potatoes that are cubed, fried, seasoned, and served hot.`,
  },
  {
    id: 17,
    title: 'Gol Gappe',
    category: 'Snacks',
    price: 69,
    img: 'https://i.ndtvimg.com/i/2017-01/gol-gappa_650x400_71485331632.jpg',
    desc: `Gol gappa (also known as pani puri) is a popular bite-size chaat consisting of a hollow, crispy-fried puffed ball that is filled with potato, chickpeas, onions, spices, and flavoured water, usually tamarind or mint, and popped into one's mouth whole.`,
  },
  {
    id: 18,
    title: 'Fish Curry',
    category: 'Dinner',
    price: 499,
    img: 'https://www.recipetineats.com/wp-content/uploads/2020/10/Goan-Fish-Curry_6-SQ.jpg',
    desc: `Malabar matthi curry, also known as fish curry, is an Indian dish. It consists of sardines semi-stewed in a Kerala-style curry with assorted vegetables, such as okra or onions. It is usually served with rice, naan, bread, or tapioca.`,
  },
  {
    id: 19,
    title: 'Butter Chicken',
    category: 'Dinner',
    price: 799,
    img: 'https://myfoodstory.com/wp-content/uploads/2016/05/Restaurant-Style-Butter-Chicken-Masala-1.jpg',
    desc: `Its mildly spicy, creamy, savoury flavour makes it more than just delicious, but accessible to almost every palate. Butter chicken originated in Delhi, the capital territory of India, sometime during the 1950s.`,
  },
  {
    id: 20,
    title: 'Dal Makhani',
    category: 'Dinner',
    price: 399,
    img: 'https://www.whiskaffair.com/wp-content/uploads/2020/06/Dal-Makhani-2-3.jpg',
    desc: `Dal makhani is a popular Indian dish made by simmering whole black lentils & red kidney beans with spices, butter & cream. Traditionally dal makhani is prepared by simmering lentils on wood/coal fire for several hours. This slow cooking for prolonged hours yield a creamy, thick and best tasting buttery dal.`,
  },
  {
    id: 21,
    title: 'Paneer-e-Labab',
    category: 'Dinner',
    price: 249,
    img: 'https://media.vogue.in/wp-content/uploads/2020/08/shahi-paneer-recipe.jpg',
    desc: `Paneer lababdar gravy is made from a spiced tomato and cashew paste that is then sautéed with onions, more spices and herbs, has a lovely tang to it and is full of flavor. The addition of sugar and cream give the dish a creamy and faintly sweet taste.`,
  },
  {
    id: 22,
    title: 'Mutton Korma',
    category: 'Dinner',
    price: 677,
    img: 'https://c.ndtvimg.com/2020-06/28gpa0a8_mutton-korma_625x300_18_June_20.jpg',
    desc: `Mutton korma is a dish made by slow cooking mutton along with yogurt, whole spices and spice powders. There are so many ways a korma is made. This is one of the versions that is close to the authentic mughlai dish except for the use of turmeric and coriander powder.`,
  },
];
export default menu;
